export const en = {
  assistant: "Assistant",
  getPro: "Get Pro",
  settings: "Settings",
  language: "Language",
  english: "English",
  russian: "Русский",
  turkmen: "Türkmençe",
  accentColor: "Accent Color",
  blue: "Blue",
  purple: "Purple",
  orange: "Orange",
  accentPreview: "Accent Preview",
  darkMode: "Dark Mode",
  privacyPolicy: "Privacy Policy",
  logOut: "Log Out",
  searchChats: "Let's search your chat history!?",
  newChat: "New Chat",
  guest: "Guest",
  askAnything: "Ask anything you want...",
  authSubtitle: "You’ll get smarter responses and can upload files and more.",
  startDeveloping: "Start developing with AI",
  hiImHere: "Hi I'm here, how can I help?",
  mayHelpSolve: "I may help to solve issues.",
  signInWithEmail: "Sign In With Email",
  signInWithGoogle: "Sign In With Google",
  signInWithGithub: "Sign In With Github",
  byContinuing: "By continuing you agree to our",
  terms: "Terms",
  and: "and",
  signInError: "Sign in failed. Please try again.",
};

export const ru = {
  assistant: "Ассистент",
  getPro: "Получить Pro",
  settings: "Настройки",
  language: "Язык",
  english: "Английский",
  russian: "Русский",
  turkmen: "Туркменский",
  accentColor: "Цвет акцента",
  blue: "Синий",
  purple: "Фиолетовый",
  orange: "Оранжевый",
  accentPreview: "Предпросмотр акцента",
  darkMode: "Тёмный режим",
  privacyPolicy: "Политика конфиденциальности",
  logOut: "Выйти",
  searchChats: "Давайте поищем в истории вашего чата!?",
  newChat: "Новый чат",
  guest: "Гость",
  askAnything: "Спросите что угодно...",
  authSubtitle:
    "Вы получите более умные ответы и сможете загружать файлы и многое другое.",
  startDeveloping: "Начните разрабатывать с ИИ",
  hiImHere: "Привет, я здесь, чем могу помочь?",
  mayHelpSolve: "Я могу помочь решить проблемы.",
  signInWithEmail: "Войти с помощью email",
  signInWithGoogle: "Войти с помощью Google",
  signInWithGithub: "Войти с помощью Github",
  byContinuing: "Продолжая, вы соглашаетесь с нашими",
  terms: "Условиями",
  and: "и",
  signInError: "Вход не удался. Пожалуйста, попробуйте снова.",
};

export const tk = {
  assistant: "Ýardamçy",
  getPro: "Pro almak",
  settings: "Sazlamalar",
  language: "Dil",
  english: "Iňlisçe",
  russian: "Orusça",
  turkmen: "Türkmençe",
  accentColor: "Öňüniň reňki",
  blue: "Gök",
  purple: "Bina",
  orange: "Sarygyl",
  accentPreview: "Öňüniň görnüşi",
  darkMode: "Gara režim",
  privacyPolicy: "Şahsyýet derejesi syýasaty",
  logOut: "Çykyş etmek",
  searchChats: "Söhbetdeşligiň taryhyňy gözläp görelärmi!?",
  newChat: "Täze söhbet",
  guest: "Myrat",
  askAnything: "Näme isleseň sorap bilersiň...",
  authSubtitle: "Agyndaky jogaplar alarsyňyz we faýllary ýüklemek we başga-da.",
  startDeveloping: "AI bilen ösüşlik başlaň",
  hiImHere: "Salam, men şu ýerde, nähili kömek edip bilerin?",
  mayHelpSolve: "Men meseleleri çözmäge kömek edip bilerin.",
  signInWithEmail: "Email bilen giriň",
  signInWithGoogle: "Google bilen giriň",
  signInWithGithub: "Github bilen giriň",
  byContinuing: "Dowam etmek arkaly, siz myňamyzyň",
  terms: "Şertlerine",
  and: "we",
  signInError: "Giriş uğursuz boldy. Gaýtadan synap görüň.",
};
